=== spc-ezual/SiteDSB/Q7-DTD.dtd
<!ELEMENT jeux (glossaire?,jeu+)>
<!ELEMENT jeu (glossaire*, titre, date_de_sortie, developpeur, editeur,genre)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT date_de_sortie (#PCDATA)>
<!ELEMENT developpeur (#PCDATA)>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT glossaire (mot+)>
<!ELEMENT mot (#PCDATA)>
<!ATTLIST mot def CDATA #REQUIRED>
<!ATTLIST jeu id CDATA #REQUIRED>
<!ATTLIST glossaire auteur CDATA>

=== spc-ezual/SiteDSB/Q8a-XML.xml
<?xml version="1.0"?>
<!DOCTYPE jeux SYSTEM "Q7-DTD.dtd">
<?xml-stylesheet href="css/Q10a-XML.css" type="text/css" ?>
<jeux>
  <glossaire auteur="tito">
      <mot def="Données">La base de données viens du site IGDB.com</mot>
      <mot def="Jeux vidéos">Forme de divertissement</mot>   
  </glossaire>
  <jeu id="1">
    <glossaire>
      <mot def="Legend of Zelda">Fait parie de la légendaire série de jeu Zelda</mot>
      <mot def="Zelda">Princesse à sauver dans la plupart des jeux The Legend of Zelda</mot>   
    </glossaire>
    <titre>The Legend of Zelda: Breath of the Wild</titre>
    <date_de_sortie>3 mars 2017</date_de_sortie>
    <developpeur>Nintendo</developpeur>
    <editeur>Nintendo</editeur>
    <genre>Action-RPG</genre>
    </jeu>
</jeux>

=== spc-ezual/SiteDSB/Q8b-XML.xml
<?xml version="1.0"?>
<!DOCTYPE jeux SYSTEM "Q7-DTD.dtd">
<?xml-stylesheet href="css/Q10a-XML.css" type="text/css" ?>
<jeux>
  <jeu id="1">
    <glossaire>
     <mot def="Zelda">Fait parie de la légendaire série de jeu Zelda</mot>
    </glossaire>
    <titre>The Legend of Zelda: Breath of the Wild</titre>
    <date_de_sortie>3 mars 2017</date_de_sortie>
    <developpeur>Nintendo</developpeur>
    <editeur>Nintendo</editeur>
    <genre>Action-RPG</genre>
  </jeu>
  <jeu id="2">
    <titre>Super Mario Odyssey</titre>
    <date_de_sortie>27 octobre 2017</date_de_sortie>
    <developpeur>Nintendo</developpeur>
    <editeur>Nintendo</editeur>
    <genre>Plateforme</genre>
  </jeu>
</jeux>
